### ISSUE TITLE
Release v2.0.0

### ISSUE THREAD

**Issue by tlvince** [angular-pouchdb/angular-pouchdb#16]
* [x] Use `$q.when` (#24)
* [x] Support nested methods list (breaking change) (#13)
* [x] Support event emitters (#12, #14, #26)
* [x] Improve test handling and coverage (#9, #10, #11, #20, #27)
* [x] Improve documentation (#8, #22, #25)
* [x] Add changelog, automate GitHub releases (#15)
* [x] Git tag, publish (#21, #29)

**Comment by tlvince** [comment]
https://github.com/angular-pouchdb/angular-pouchdb/releases/tag/v2.0.0
